import type { ConfigPrimitive, FilamentProfile, GeneratedConfig, PrinterProfile } from "@layerai/shared-types";
import { BAMBU_PARAM_MAP } from "./bambu-param-map.js";
import { validateStandaloneBambuJsonText, validateStandaloneIniText } from "./validation.js";

const PERCENT_KEYS = new Set(["fill_density"]);

function serializeValue(key: string, value: ConfigPrimitive): string {
  if (typeof value === "boolean") return value ? "1" : "0";
  if (typeof value === "number" && PERCENT_KEYS.has(key)) return `${value}%`;
  return String(value);
}

function serializeBambuValue(key: string, value: ConfigPrimitive): string {
  if (key === "support_material_style") return value === "organic" ? "tree(auto)" : "normal(auto)";
  return serializeValue(key, value);
}

function mappedBambuKey(key: string): string {
  const mapped = BAMBU_PARAM_MAP[key];
  if (!mapped) throw new Error(`Export Bambu/Creality incomplet : le paramètre « ${key} » n'a pas de correspondance slicer.`);
  return mapped;
}

function bedShapeToString(printer: PrinterProfile): string {
  return printer.bedShape.map((p) => `${p.x}x${p.y}`).join(",");
}

/** Identity keys that must accompany the generated print parameters for PrusaSlicer to treat the file as a complete, self-consistent FFF profile. */
function buildIdentityKeys(printer: PrinterProfile, filament: FilamentProfile): Record<string, ConfigPrimitive> {
  return {
    printer_technology: "FFF",
    printer_model: printer.id,
    nozzle_diameter: printer.defaultNozzleDiameterMm,
    bed_shape: bedShapeToString(printer),
    max_print_height: printer.maxPrintHeightMm,
    filament_type: filament.materialType,
    filament_diameter: filament.diameterMm,
    filament_density: filament.densityGCm3,
  };
}

/**
 * Builds Metadata/Slic3r_PE.config content. PrusaSlicer's reader (`ConfigBase::
 * load_from_gcode_string_legacy`) walks the file *backward from the end* looking for lines
 * matching exactly `; key = value` (semicolon, one space, key, " = ", value) and stops at the
 * first non-matching line - so every config line must be contiguous at the end of the file, and
 * the leading header/blank line must NOT itself look like `key = value`.
 */
export function buildPrintConfigText(config: GeneratedConfig, printer: PrinterProfile, filament: FilamentProfile): string {
  const identity = buildIdentityKeys(printer, filament);
  const lines: string[] = ["; generated by LayerAI", ""];

  for (const [key, value] of Object.entries(identity)) {
    lines.push(`; ${key} = ${serializeValue(key, value)}`);
  }
  for (const [key, entry] of Object.entries(config)) {
    lines.push(`; ${key} = ${serializeValue(key, entry.value)}`);
  }

  return lines.join("\n") + "\n";
}

/**
 * Builds Metadata/print_profile.config for a Bambu Lab target printer. BambuStudio's own writer
 * (`_BBS_3MF_Exporter::_add_print_config_file_to_archive`) uses the identical `; key = value`
 * comment-line convention as PrusaSlicer's Slic3r_PE.config, just under a different filename and
 * BambuStudio's own parameter vocabulary (see bambu-param-map.ts). Best-effort: field names are
 * confirmed against BambuStudio's source, but not round-trip tested against a real install.
 */
export function buildBambuPrintConfigText(config: GeneratedConfig, printer: PrinterProfile, filament: FilamentProfile): string {
  const lines: string[] = ["; generated by LayerAI", ""];

  lines.push(`; printer_model = ${printer.id}`);
  lines.push(`; nozzle_diameter = ${printer.defaultNozzleDiameterMm}`);
  lines.push(`; filament_type = ${filament.materialType}`);

  for (const [key, entry] of Object.entries(config)) {
    const bambuKey = mappedBambuKey(key);
    lines.push(`; ${bambuKey} = ${serializeBambuValue(key, entry.value)}`);
  }

  return lines.join("\n") + "\n";
}

/**
 * Builds a standalone, importable PrusaSlicer config .ini (File > Import Config): plain
 * `key = value` lines, no semicolon-comment framing - unlike Slic3r_PE.config, this is parsed by
 * `ConfigBase::load_from_ini` (boost property_tree), a standard INI reader.
 */
export function buildStandaloneIniText(config: GeneratedConfig, printer: PrinterProfile, filament: FilamentProfile): string {
  const identity = buildIdentityKeys(printer, filament);
  const lines: string[] = ["# generated by LayerAI", ""];

  for (const [key, value] of Object.entries(identity)) {
    lines.push(`${key} = ${serializeValue(key, value)}`);
  }
  for (const [key, entry] of Object.entries(config)) {
    lines.push(`${key} = ${serializeValue(key, entry.value)}`);
  }

  const text = lines.join("\n") + "\n";
  validateStandaloneIniText(text);
  return text;
}

/**
 * Builds a standalone, importable BambuStudio process preset .json (File > Import > Import
 * Configs, which accepts single *.json preset files directly). Shape confirmed against both a
 * real shipped BambuStudio process preset (type/name/from/instantiation + flat settings keys) and
 * `Preset::save` in BambuStudio's own source (`from_str = "User"` for user-authored presets).
 * Same best-effort caveat as buildBambuPrintConfigText: field names are mapped via
 * bambu-param-map.ts, not round-trip tested against a real BambuStudio install.
 */
export function buildStandaloneBambuJsonText(config: GeneratedConfig, printer: PrinterProfile, filament: FilamentProfile): string {
  const profile: Record<string, unknown> = {
    type: "process",
    name: `LayerAI - ${printer.name}`,
    from: "User",
    instantiation: "true",
    printer_model: printer.id,
    nozzle_diameter: String(printer.defaultNozzleDiameterMm),
    filament_type: filament.materialType,
    compatible_printers: [printer.name],
  };

  for (const [key, entry] of Object.entries(config)) {
    const bambuKey = mappedBambuKey(key);
    profile[bambuKey] = serializeBambuValue(key, entry.value);
  }

  const text = JSON.stringify(profile, null, 4) + "\n";
  validateStandaloneBambuJsonText(text);
  return text;
}
