import type { ConfigPrimitive, FilamentProfile, GeneratedConfig, PrinterProfile } from "@layerai/shared-types";
import { BAMBU_PARAM_MAP, BAMBU_UNMAPPED_KEYS } from "./bambu-param-map.js";

const PERCENT_KEYS = new Set(["fill_density"]);

function serializeValue(key: string, value: ConfigPrimitive): string {
  if (typeof value === "boolean") return value ? "1" : "0";
  if (typeof value === "number" && PERCENT_KEYS.has(key)) return `${value}%`;
  return String(value);
}

function bedShapeToString(printer: PrinterProfile): string {
  return printer.bedShape.map((p) => `${p.x}x${p.y}`).join(",");
}

/** Identity keys that must accompany the generated print parameters for PrusaSlicer to treat the file as a complete, self-consistent FFF profile. */
function buildIdentityKeys(printer: PrinterProfile, filament: FilamentProfile): Record<string, ConfigPrimitive> {
  return {
    printer_technology: "FFF",
    printer_model: printer.id,
    nozzle_diameter: printer.defaultNozzleDiameterMm,
    bed_shape: bedShapeToString(printer),
    max_print_height: printer.maxPrintHeightMm,
    filament_type: filament.materialType,
    filament_diameter: filament.diameterMm,
    filament_density: filament.densityGCm3,
  };
}

/**
 * Builds Metadata/Slic3r_PE.config content. PrusaSlicer's reader (`ConfigBase::
 * load_from_gcode_string_legacy`) walks the file *backward from the end* looking for lines
 * matching exactly `; key = value` (semicolon, one space, key, " = ", value) and stops at the
 * first non-matching line - so every config line must be contiguous at the end of the file, and
 * the leading header/blank line must NOT itself look like `key = value`.
 */
export function buildPrintConfigText(config: GeneratedConfig, printer: PrinterProfile, filament: FilamentProfile): string {
  const identity = buildIdentityKeys(printer, filament);
  const lines: string[] = ["; generated by LayerAI", ""];

  for (const [key, value] of Object.entries(identity)) {
    lines.push(`; ${key} = ${serializeValue(key, value)}`);
  }
  for (const [key, entry] of Object.entries(config)) {
    lines.push(`; ${key} = ${serializeValue(key, entry.value)}`);
  }

  return lines.join("\n") + "\n";
}

/**
 * Builds Metadata/print_profile.config for a Bambu Lab target printer. BambuStudio's own writer
 * (`_BBS_3MF_Exporter::_add_print_config_file_to_archive`) uses the identical `; key = value`
 * comment-line convention as PrusaSlicer's Slic3r_PE.config, just under a different filename and
 * BambuStudio's own parameter vocabulary (see bambu-param-map.ts). Best-effort: field names are
 * confirmed against BambuStudio's source, but not round-trip tested against a real install.
 */
export function buildBambuPrintConfigText(config: GeneratedConfig, printer: PrinterProfile, filament: FilamentProfile): string {
  const lines: string[] = ["; generated by LayerAI", ""];

  lines.push(`; printer_model = ${printer.id}`);
  lines.push(`; nozzle_diameter = ${printer.defaultNozzleDiameterMm}`);
  lines.push(`; filament_type = ${filament.materialType}`);

  for (const [key, entry] of Object.entries(config)) {
    if (BAMBU_UNMAPPED_KEYS.has(key)) continue;
    const bambuKey = BAMBU_PARAM_MAP[key];
    if (!bambuKey) continue;
    lines.push(`; ${bambuKey} = ${serializeValue(key, entry.value)}`);
  }

  return lines.join("\n") + "\n";
}

/**
 * Builds a standalone, importable PrusaSlicer config .ini (File > Import Config): plain
 * `key = value` lines, no semicolon-comment framing - unlike Slic3r_PE.config, this is parsed by
 * `ConfigBase::load_from_ini` (boost property_tree), a standard INI reader.
 */
export function buildStandaloneIniText(config: GeneratedConfig, printer: PrinterProfile, filament: FilamentProfile): string {
  const identity = buildIdentityKeys(printer, filament);
  const lines: string[] = ["# generated by LayerAI", ""];

  for (const [key, value] of Object.entries(identity)) {
    lines.push(`${key} = ${serializeValue(key, value)}`);
  }
  for (const [key, entry] of Object.entries(config)) {
    lines.push(`${key} = ${serializeValue(key, entry.value)}`);
  }

  return lines.join("\n") + "\n";
}
