export const IpcChannels = {
  importOpenDialog: "import:open-dialog",
  importReadDropped: "import:read-dropped",
  analysisRun: "analysis:run",
  analysisRescale: "analysis:rescale",
  analysisReorient: "analysis:reorient",
  configGenerate: "config:generate",
  profileDbGetPrinters: "profiledb:get-printers",
  profileDbGetFilaments: "profiledb:get-filaments",
  exportThreeMf: "export:threemf",
  exportPdfReport: "export:pdf-report",
  exportIni: "export:ini",
  slicerOpen: "slicer:open",
  learningRecordOutcome: "learning:record-outcome",
  customProfilesList: "custom-profiles:list",
  customProfilesSave: "custom-profiles:save",
  customProfilesDelete: "custom-profiles:delete",
  settingsGet: "settings:get",
  settingsSetOnboardingCompleted: "settings:set-onboarding-completed",
  settingsSetLanguage: "settings:set-language",
  menuAction: "menu:action",
  appGetVersion: "app:get-version",
  aiGetSettings: "ai:get-settings",
  aiSaveProvider: "ai:save-provider",
  aiDeleteProvider: "ai:delete-provider",
  aiSetDefaultProvider: "ai:set-default-provider",
  aiSetCloudIntentEnabled: "ai:set-cloud-intent-enabled",
  aiTestProvider: "ai:test-provider",
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];
