export type InvoiceLanguage = "fr" | "en" | "de" | "es" | "it";

export interface InvoiceText {
  locale: string;
  invoice: string;
  issueDate: string;
  dueDate: string;
  issuer: string;
  client: string;
  shareCapital: string;
  vatNumber: string;
  description: string;
  quantity: string;
  unitPrice: string;
  totalExVat: string;
  vat: string;
  totalIncVat: string;
  vatExemption: string;
  paymentTerms: (days: number, dueDate: string, iban?: string) => string;
  latePayment: string;
  noDiscount: string;
  generatedBy: string;
}

export const INVOICE_TEXT: Record<InvoiceLanguage, InvoiceText> = {
  fr: { locale: "fr-FR", invoice: "FACTURE", issueDate: "Date d’émission", dueDate: "Date d’échéance", issuer: "Émetteur", client: "Client", shareCapital: "Capital social", vatNumber: "N° TVA intracommunautaire", description: "Désignation", quantity: "Quantité", unitPrice: "PU HT", totalExVat: "Total HT", vat: "TVA", totalIncVat: "Total TTC", vatExemption: "TVA non applicable, art. 293 B du CGI", paymentTerms: (days, due, iban) => `Conditions de règlement : paiement à ${days} jours (échéance le ${due}).${iban ? ` Coordonnées bancaires : ${iban}.` : ""}`, latePayment: "En cas de retard de paiement, une pénalité au taux d’intérêt légal en vigueur majoré, ainsi qu’une indemnité forfaitaire pour frais de recouvrement de 40 € (art. L441-10 et D441-5 du Code de commerce), seront exigibles sans rappel.", noDiscount: "Pas d’escompte pour paiement anticipé.", generatedBy: "Facture générée par LayerAI" },
  en: { locale: "en-GB", invoice: "INVOICE", issueDate: "Issue date", dueDate: "Due date", issuer: "Issuer", client: "Client", shareCapital: "Share capital", vatNumber: "EU VAT number", description: "Description", quantity: "Quantity", unitPrice: "Unit price excl. VAT", totalExVat: "Total excl. VAT", vat: "VAT", totalIncVat: "Total incl. VAT", vatExemption: "VAT not applicable, Article 293 B of the French General Tax Code", paymentTerms: (days, due, iban) => `Payment terms: payment within ${days} days (due ${due}).${iban ? ` Bank details: ${iban}.` : ""}`, latePayment: "In the event of late payment, the increased statutory interest rate and a fixed €40 recovery fee (Articles L441-10 and D441-5 of the French Commercial Code) become payable without prior notice.", noDiscount: "No discount for early payment.", generatedBy: "Invoice generated by LayerAI" },
  de: { locale: "de-DE", invoice: "RECHNUNG", issueDate: "Ausstellungsdatum", dueDate: "Fälligkeitsdatum", issuer: "Aussteller", client: "Kunde", shareCapital: "Stammkapital", vatNumber: "EU-USt-IdNr.", description: "Bezeichnung", quantity: "Menge", unitPrice: "Einzelpreis netto", totalExVat: "Summe netto", vat: "MwSt.", totalIncVat: "Summe brutto", vatExemption: "Keine Mehrwertsteuer gemäß Art. 293 B des französischen Steuergesetzbuchs", paymentTerms: (days, due, iban) => `Zahlungsbedingungen: Zahlung innerhalb von ${days} Tagen (fällig am ${due}).${iban ? ` Bankverbindung: ${iban}.` : ""}`, latePayment: "Bei Zahlungsverzug werden der erhöhte gesetzliche Zinssatz sowie eine pauschale Beitreibungsentschädigung von 40 € (Art. L441-10 und D441-5 des französischen Handelsgesetzbuchs) ohne Mahnung fällig.", noDiscount: "Kein Skonto bei vorzeitiger Zahlung.", generatedBy: "Rechnung erstellt mit LayerAI" },
  es: { locale: "es-ES", invoice: "FACTURA", issueDate: "Fecha de emisión", dueDate: "Fecha de vencimiento", issuer: "Emisor", client: "Cliente", shareCapital: "Capital social", vatNumber: "N.º IVA intracomunitario", description: "Descripción", quantity: "Cantidad", unitPrice: "Precio unitario sin IVA", totalExVat: "Total sin IVA", vat: "IVA", totalIncVat: "Total con IVA", vatExemption: "IVA no aplicable, art. 293 B del Código General Tributario francés", paymentTerms: (days, due, iban) => `Condiciones de pago: pago en ${days} días (vencimiento: ${due}).${iban ? ` Datos bancarios: ${iban}.` : ""}`, latePayment: "En caso de demora, serán exigibles sin previo aviso el interés legal incrementado y una indemnización fija de 40 € por gastos de cobro (arts. L441-10 y D441-5 del Código de Comercio francés).", noDiscount: "Sin descuento por pronto pago.", generatedBy: "Factura generada por LayerAI" },
  it: { locale: "it-IT", invoice: "FATTURA", issueDate: "Data di emissione", dueDate: "Data di scadenza", issuer: "Emittente", client: "Cliente", shareCapital: "Capitale sociale", vatNumber: "N. IVA intracomunitaria", description: "Descrizione", quantity: "Quantità", unitPrice: "Prezzo unitario IVA escl.", totalExVat: "Totale IVA escl.", vat: "IVA", totalIncVat: "Totale IVA incl.", vatExemption: "IVA non applicabile, art. 293 B del Codice tributario generale francese", paymentTerms: (days, due, iban) => `Condizioni di pagamento: pagamento entro ${days} giorni (scadenza ${due}).${iban ? ` Coordinate bancarie: ${iban}.` : ""}`, latePayment: "In caso di ritardo saranno esigibili senza preavviso il tasso d’interesse legale maggiorato e un’indennità forfettaria di 40 € per le spese di recupero (artt. L441-10 e D441-5 del Codice di commercio francese).", noDiscount: "Nessuno sconto per pagamento anticipato.", generatedBy: "Fattura generata da LayerAI" },
};
